[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+bmi2", "-C", "target-feature=+adx"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-cpu=cortex-a15"]
